Create action
ottofeller/publish-npm-gh-action pull request #1
Opened 2021-12-24 19:40 UTC by quesabe

2021-12-28 20:25 UTC, gvidon requested changes

2021-12-28 20:25 UTC, gvidon commented on action.yml
> +        command: npm publish
@quesabe let's allow for setting `--access` value from the input params.

2021-12-28 20:25 UTC, gvidon commented on action.yml
> +description: 'A GitHub action publishing an npm package'
@quesabe I would stick to using double quotes.

2021-12-28 20:25 UTC, gvidon commented on action.yml
> +  commit-hash:
@quesabe can we make the commit hash as optional param and by default publish from the primary branch?

2021-12-28 20:25 UTC, gvidon commented on action.yml
> +  node-version:
@quesabe let's set 16 as a default value.

2021-12-28 20:25 UTC, gvidon commented on action.yml
> +  registry-url:
@quesabe are these params really optional? Won't action fail if it doesn't find them to be set?

2021-12-29 18:27 UTC, quesabe commented on action.yml
> +  registry-url:
Yes, they are. The optionality is described in node-setup readme. As far as I remember, node would default to 12. registry-url is written to the `.npmrc` file and if not supplied nom will use default value of `https://registry.npmjs.org`.

2021-12-30 15:00 UTC, quesabe commented on action.yml
> +description: 'A GitHub action publishing an npm package'
Removed most of single quotes, the remaining updated to double.

2021-12-30 15:01 UTC, quesabe commented on action.yml
> +  commit-hash:
It is already optional per actions/checkout docs. Updated descriptions.

2022-01-06 09:31 UTC, gvidon approved these changes

2022-01-06 09:31 UTC, merged